// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQJA-3Zkztu3pYlQHK86K_f49syWW5Ak',
    appId: '1:365347623914:web:4c5ffe631331be37afd893',
    messagingSenderId: '365347623914',
    projectId: 'fir-877f2',
    authDomain: 'fir-877f2.firebaseapp.com',
    storageBucket: 'fir-877f2.firebasestorage.app',
    measurementId: 'G-B6BR9C616Q',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-A541nsZoliXmCaAwlvaYN1AQszrbINA',
    appId: '1:365347623914:ios:8c452809fdbd94fcafd893',
    messagingSenderId: '365347623914',
    projectId: 'fir-877f2',
    storageBucket: 'fir-877f2.firebasestorage.app',
    iosClientId: '365347623914-4psmn9ud2s7k6s7mtgueojbm9oeqgt9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-A541nsZoliXmCaAwlvaYN1AQszrbINA',
    appId: '1:365347623914:ios:8c452809fdbd94fcafd893',
    messagingSenderId: '365347623914',
    projectId: 'fir-877f2',
    storageBucket: 'fir-877f2.firebasestorage.app',
    iosClientId: '365347623914-4psmn9ud2s7k6s7mtgueojbm9oeqgt9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxQJA-3Zkztu3pYlQHK86K_f49syWW5Ak',
    appId: '1:365347623914:web:bfdfa69a313bf6c0afd893',
    messagingSenderId: '365347623914',
    projectId: 'fir-877f2',
    authDomain: 'fir-877f2.firebaseapp.com',
    storageBucket: 'fir-877f2.firebasestorage.app',
    measurementId: 'G-TYL1ZJ7Y38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARK3zh3bdp_ANyTI_F26asOf3s3AIMWxA',
    appId: '1:365347623914:android:58aff25899425246afd893',
    messagingSenderId: '365347623914',
    projectId: 'fir-877f2',
    storageBucket: 'fir-877f2.firebasestorage.app',
  );

}